#!/usr/bin/env Rscript

# Generate inst/AUTHORS and inst/LICENCE.note for Rust crate dependencies.
#
# This follows the CRAN-oriented Rust authorship/licence-note pattern used by
# string2path and Rsassy, but reads Cargo metadata from the opt-in Savvy adapter
# crate instead of requiring a vendored tarball during normal development.
#
# Run from the Rwasmtime package root:
#   Rscript tools/update-authors.R

root <- normalizePath(".", mustWork = TRUE)
manifest <- file.path(root, "src", "savvy", "Cargo.toml")
if (!file.exists(manifest)) stop("missing Savvy adapter Cargo.toml: ", manifest, call. = FALSE)
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  stop("jsonlite is required to parse cargo metadata for authorship generation", call. = FALSE)
}

run <- function(cmd, args, wd = root) {
  out <- tempfile("rwasmtime-cargo-metadata-")
  err <- tempfile("rwasmtime-cargo-metadata-err-")
  old <- getwd()
  on.exit(setwd(old), add = TRUE)
  on.exit(unlink(c(out, err), force = TRUE), add = TRUE)
  setwd(wd)
  status <- system2(cmd, args, stdout = out, stderr = err)
  if (!identical(status, 0L)) {
    msg <- paste(readLines(err, warn = FALSE), collapse = "\n")
    stop(sprintf("%s failed with status %s\n%s", cmd, status, msg), call. = FALSE)
  }
  paste(readLines(out, warn = FALSE), collapse = "\n")
}

metadata_json <- run("cargo", c(
  "metadata",
  "--locked",
  "--format-version", "1",
  "--manifest-path", manifest
))
metadata <- jsonlite::fromJSON(metadata_json, simplifyVector = FALSE)
packages <- metadata$packages

`%||%` <- function(x, y) if (is.null(x) || length(x) == 0L || is.na(x)) y else x

is_external <- vapply(packages, function(pkg) !is.null(pkg$source), logical(1))
external <- packages[is_external]
external <- external[order(
  vapply(external, function(pkg) pkg$name %||% "", character(1)),
  vapply(external, function(pkg) pkg$version %||% "", character(1))
)]

format_authors <- function(authors, indent = "  ") {
  if (is.null(authors) || !length(authors)) {
    return(paste0(indent, "Not listed in Cargo metadata; see upstream crate license files."))
  }
  authors <- gsub("\\s+<[^>]+>", "", unlist(authors, use.names = FALSE))
  authors <- authors[nzchar(authors)]
  if (!length(authors)) {
    return(paste0(indent, "Not listed in Cargo metadata; see upstream crate license files."))
  }
  paste0(indent, authors, collapse = "\n")
}

format_scalar <- function(x) {
  x <- x %||% NA_character_
  if (is.na(x) || !nzchar(x)) "Not listed in Cargo metadata" else x
}

crate_file_hint <- function(pkg) {
  source <- pkg$source %||% "registry"
  sprintf("Cargo dependency %s %s from %s", pkg$name, pkg$version, source)
}

dir.create(file.path(root, "inst"), showWarnings = FALSE)

writeLines(
  c(
    "Generated by tools/update-authors.R; do not edit by hand.",
    "",
    "Rwasmtime package code:",
    "  Sounkou Mahamane Toure",
    "",
    "Local Rust crates in this repository:",
    "  rwasmtime (src/rust)",
    "  rwasmtime_savvy (src/savvy)",
    "",
    "The authors of Rust crate dependencies used by the opt-in native backend:",
    "",
    unlist(lapply(external, function(pkg) {
      c(
        sprintf("%s (version %s):", pkg$name, pkg$version),
        format_authors(pkg$authors),
        ""
      )
    }), use.names = FALSE)
  ),
  con = file.path(root, "inst", "AUTHORS")
)

writeLines(
  c(
    "Generated by tools/update-authors.R; do not edit by hand.",
    "",
    "Rwasmtime includes Rust source code and can optionally build a native",
    "Rust/Wasmtime backend as part of the package native library. Default",
    "package builds use C stubs and do not compile the Rust backend.",
    "",
    "This generated notice follows the CRAN-oriented Rust authorship/licence-note",
    "pattern used by Hiroaki Yutani's string2path package:",
    "https://github.com/yutannihilation/string2path/blob/main/update_authors.R",
    "and discussed at:",
    "https://yutani.rbind.io/post/rust-and-cran-repository-policy/",
    "",
    "Rwasmtime package code:",
    "- Copyright: Sounkou Mahamane Toure",
    "- License: GPL (>= 3), as declared in DESCRIPTION.",
    "",
    "Local Rust crates in this repository:",
    "- rwasmtime (src/rust): package code, GPL (>= 3).",
    "- rwasmtime_savvy (src/savvy): package adapter code, GPL (>= 3).",
    "",
    "Rust crate dependency components for the opt-in native backend:",
    ""
  ),
  con = file.path(root, "inst", "LICENCE.note")
)

entry_text <- unlist(lapply(external, function(pkg) {
  c(
    "------------------------------",
    sprintf("Name:       %s", pkg$name),
    sprintf("Version:    %s", pkg$version),
    sprintf("Files:      %s", crate_file_hint(pkg)),
    sprintf("Authors:    %s", if (!is.null(pkg$authors) && length(pkg$authors)) paste(gsub("\\s+<[^>]+>", "", unlist(pkg$authors, use.names = FALSE)), collapse = ", ") else "Not listed in Cargo metadata; see upstream crate license files."),
    sprintf("License:    %s", format_scalar(pkg$license)),
    sprintf("Repository: %s", format_scalar(pkg$repository)),
    ""
  )
}), use.names = FALSE)

cat(paste(entry_text, collapse = "\n"), file = file.path(root, "inst", "LICENCE.note"), append = TRUE)
cat("\nThis notice documents third-party Rust crate components and does not modify the license terms declared for Rwasmtime itself.\n", file = file.path(root, "inst", "LICENCE.note"), append = TRUE)

message("Wrote inst/AUTHORS and inst/LICENCE.note")
