#include <Rinternals.h>
#include <stdint.h>

#include "rust/api.h"

/*
 * Default native no-backend implementations of the Savvy-generated FFI symbols.
 *
 * src/init.c is fully generated by Savvy; this file only provides the
 * expected generated symbol names when the real Rust backend is not linked in
 * the default native package build. These are not custom .Call entries.
 */

static SEXP rwasmtime_savvy_pending_error(void) {
  SEXP msg = Rf_mkChar("Rwasmtime's native Rust/Wasmtime backend is not available in this package build");
  return (SEXP)(((uintptr_t)msg) | (uintptr_t)1);
}

SEXP savvy_rwasmtime_backend_status__ffi(void) {
  return Rf_mkString("pending");
}

SEXP savvy_RwasmtimeNativeInstance_call_core__ffi(
    SEXP self__,
    SEXP c_arg__export,
    SEXP c_arg__args) {
  (void)self__;
  (void)c_arg__export;
  (void)c_arg__args;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeInstance_memory_grow__ffi(
    SEXP self__,
    SEXP c_arg__name,
    SEXP c_arg__pages) {
  (void)self__;
  (void)c_arg__name;
  (void)c_arg__pages;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeInstance_memory_read__ffi(
    SEXP self__,
    SEXP c_arg__name,
    SEXP c_arg__offset,
    SEXP c_arg__len) {
  (void)self__;
  (void)c_arg__name;
  (void)c_arg__offset;
  (void)c_arg__len;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeInstance_memory_size__ffi(
    SEXP self__,
    SEXP c_arg__name) {
  (void)self__;
  (void)c_arg__name;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeInstance_memory_write__ffi(
    SEXP self__,
    SEXP c_arg__name,
    SEXP c_arg__offset,
    SEXP c_arg__value) {
  (void)self__;
  (void)c_arg__name;
  (void)c_arg__offset;
  (void)c_arg__value;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeInstance_wasi_output__ffi(SEXP self__) {
  (void)self__;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeModule_instantiate__ffi(
    SEXP self__,
    SEXP c_arg__memory_bytes,
    SEXP c_arg__table_elements,
    SEXP c_arg__instances,
    SEXP c_arg__fuel,
    SEXP c_arg__wall_time_ms) {
  (void)self__;
  (void)c_arg__memory_bytes;
  (void)c_arg__table_elements;
  (void)c_arg__instances;
  (void)c_arg__fuel;
  (void)c_arg__wall_time_ms;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeModule_instantiate_callbacks__ffi(
    SEXP self__,
    SEXP c_arg__callback_modules,
    SEXP c_arg__callback_names,
    SEXP c_arg__callback_functions,
    SEXP c_arg__memory_bytes,
    SEXP c_arg__table_elements,
    SEXP c_arg__instances,
    SEXP c_arg__fuel,
    SEXP c_arg__wall_time_ms) {
  (void)self__;
  (void)c_arg__callback_modules;
  (void)c_arg__callback_names;
  (void)c_arg__callback_functions;
  (void)c_arg__memory_bytes;
  (void)c_arg__table_elements;
  (void)c_arg__instances;
  (void)c_arg__fuel;
  (void)c_arg__wall_time_ms;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeModule_instantiate_wasi_p1__ffi(
    SEXP self__,
    SEXP c_arg__args,
    SEXP c_arg__env_names,
    SEXP c_arg__env_values,
    SEXP c_arg__preopen_guest,
    SEXP c_arg__preopen_host,
    SEXP c_arg__preopen_readonly,
    SEXP c_arg__stdin,
    SEXP c_arg__stdout,
    SEXP c_arg__stderr,
    SEXP c_arg__memory_bytes,
    SEXP c_arg__table_elements,
    SEXP c_arg__instances,
    SEXP c_arg__fuel,
    SEXP c_arg__wall_time_ms,
    SEXP c_arg__input) {
  (void)self__;
  (void)c_arg__args;
  (void)c_arg__env_names;
  (void)c_arg__env_values;
  (void)c_arg__preopen_guest;
  (void)c_arg__preopen_host;
  (void)c_arg__preopen_readonly;
  (void)c_arg__stdin;
  (void)c_arg__stdout;
  (void)c_arg__stderr;
  (void)c_arg__memory_bytes;
  (void)c_arg__table_elements;
  (void)c_arg__instances;
  (void)c_arg__fuel;
  (void)c_arg__wall_time_ms;
  (void)c_arg__input;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeModule_serialize__ffi(SEXP self__) {
  (void)self__;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_build__ffi(
    SEXP c_arg__compiler_strategy,
    SEXP c_arg__opt_level,
    SEXP c_arg__parallel,
    SEXP c_arg__component_model,
    SEXP c_arg__component_model_async,
    SEXP c_arg__simd,
    SEXP c_arg__relaxed_simd,
    SEXP c_arg__relaxed_simd_deterministic,
    SEXP c_arg__bulk_memory,
    SEXP c_arg__multi_memory,
    SEXP c_arg__memory64,
    SEXP c_arg__threads,
    SEXP c_arg__gc) {
  (void)c_arg__compiler_strategy;
  (void)c_arg__opt_level;
  (void)c_arg__parallel;
  (void)c_arg__component_model;
  (void)c_arg__component_model_async;
  (void)c_arg__simd;
  (void)c_arg__relaxed_simd;
  (void)c_arg__relaxed_simd_deterministic;
  (void)c_arg__bulk_memory;
  (void)c_arg__multi_memory;
  (void)c_arg__memory64;
  (void)c_arg__threads;
  (void)c_arg__gc;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_call_core__ffi(
    SEXP self__,
    SEXP c_arg__module,
    SEXP c_arg__export,
    SEXP c_arg__args,
    SEXP c_arg__memory_bytes,
    SEXP c_arg__table_elements,
    SEXP c_arg__instances,
    SEXP c_arg__fuel,
    SEXP c_arg__wall_time_ms) {
  (void)self__;
  (void)c_arg__module;
  (void)c_arg__export;
  (void)c_arg__args;
  (void)c_arg__memory_bytes;
  (void)c_arg__table_elements;
  (void)c_arg__instances;
  (void)c_arg__fuel;
  (void)c_arg__wall_time_ms;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_compile_core__ffi(
    SEXP self__,
    SEXP c_arg__module) {
  (void)self__;
  (void)c_arg__module;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_component_exports__ffi(
    SEXP self__,
    SEXP c_arg__component) {
  (void)self__;
  (void)c_arg__component;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_component_imports__ffi(
    SEXP self__,
    SEXP c_arg__component) {
  (void)self__;
  (void)c_arg__component;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_deserialize_core__ffi(
    SEXP self__,
    SEXP c_arg__bytes) {
  (void)self__;
  (void)c_arg__bytes;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_instantiate_core__ffi(
    SEXP self__,
    SEXP c_arg__module,
    SEXP c_arg__memory_bytes,
    SEXP c_arg__table_elements,
    SEXP c_arg__instances,
    SEXP c_arg__fuel,
    SEXP c_arg__wall_time_ms) {
  (void)self__;
  (void)c_arg__module;
  (void)c_arg__memory_bytes;
  (void)c_arg__table_elements;
  (void)c_arg__instances;
  (void)c_arg__fuel;
  (void)c_arg__wall_time_ms;
  return rwasmtime_savvy_pending_error();
}

SEXP savvy_RwasmtimeNativeRuntime_run_wasi_p1__ffi(
    SEXP self__,
    SEXP c_arg__module,
    SEXP c_arg__args,
    SEXP c_arg__env_names,
    SEXP c_arg__env_values,
    SEXP c_arg__preopen_guest,
    SEXP c_arg__preopen_host,
    SEXP c_arg__preopen_readonly,
    SEXP c_arg__stdin,
    SEXP c_arg__stdout,
    SEXP c_arg__stderr,
    SEXP c_arg__memory_bytes,
    SEXP c_arg__table_elements,
    SEXP c_arg__instances,
    SEXP c_arg__fuel,
    SEXP c_arg__wall_time_ms,
    SEXP c_arg__input) {
  (void)self__;
  (void)c_arg__module;
  (void)c_arg__args;
  (void)c_arg__env_names;
  (void)c_arg__env_values;
  (void)c_arg__preopen_guest;
  (void)c_arg__preopen_host;
  (void)c_arg__preopen_readonly;
  (void)c_arg__stdin;
  (void)c_arg__stdout;
  (void)c_arg__stderr;
  (void)c_arg__memory_bytes;
  (void)c_arg__table_elements;
  (void)c_arg__instances;
  (void)c_arg__fuel;
  (void)c_arg__wall_time_ms;
  (void)c_arg__input;
  return rwasmtime_savvy_pending_error();
}
