# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib Rwasmtime, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_Rwasmtime__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_Rwasmtime__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Return whether the generated Savvy adapter is linked to the native backend.
#' @noRd
`rwasmtime_backend_status` <- function() {
  .Call(savvy_rwasmtime_backend_status__impl)
}

### wrapper functions for RwasmtimeNativeInstance

`RwasmtimeNativeInstance_call_core` <- function(self) {
  function(`export`, `args`) {
    .Call(savvy_RwasmtimeNativeInstance_call_core__impl, `self`, `export`, `args`)
  }
}

`RwasmtimeNativeInstance_memory_grow` <- function(self) {
  function(`name`, `pages`) {
    .Call(savvy_RwasmtimeNativeInstance_memory_grow__impl, `self`, `name`, `pages`)
  }
}

`RwasmtimeNativeInstance_memory_read` <- function(self) {
  function(`name`, `offset`, `len`) {
    .Call(savvy_RwasmtimeNativeInstance_memory_read__impl, `self`, `name`, `offset`, `len`)
  }
}

`RwasmtimeNativeInstance_memory_size` <- function(self) {
  function(`name`) {
    .Call(savvy_RwasmtimeNativeInstance_memory_size__impl, `self`, `name`)
  }
}

`RwasmtimeNativeInstance_memory_write` <- function(self) {
  function(`name`, `offset`, `value`) {
    .Call(savvy_RwasmtimeNativeInstance_memory_write__impl, `self`, `name`, `offset`, `value`)
  }
}

`RwasmtimeNativeInstance_wasi_output` <- function(self) {
  function() {
    .Call(savvy_RwasmtimeNativeInstance_wasi_output__impl, `self`)
  }
}

`.savvy_wrap_RwasmtimeNativeInstance` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`call_core` <- `RwasmtimeNativeInstance_call_core`(ptr)
  e$`memory_grow` <- `RwasmtimeNativeInstance_memory_grow`(ptr)
  e$`memory_read` <- `RwasmtimeNativeInstance_memory_read`(ptr)
  e$`memory_size` <- `RwasmtimeNativeInstance_memory_size`(ptr)
  e$`memory_write` <- `RwasmtimeNativeInstance_memory_write`(ptr)
  e$`wasi_output` <- `RwasmtimeNativeInstance_wasi_output`(ptr)

  class(e) <- c("Rwasmtime::RwasmtimeNativeInstance", "RwasmtimeNativeInstance", "savvy_Rwasmtime__sealed")
  e
}


#' Persistent core Wasm instance owned by the Savvy adapter.
#' @noRd
`RwasmtimeNativeInstance` <- new.env(parent = emptyenv())

### associated functions for RwasmtimeNativeInstance



class(`RwasmtimeNativeInstance`) <- c("Rwasmtime::RwasmtimeNativeInstance__bundle", "savvy_Rwasmtime__sealed")

#' @export
`print.Rwasmtime::RwasmtimeNativeInstance__bundle` <- function(x, ...) {
  cat('Rwasmtime::RwasmtimeNativeInstance\n')
}

### wrapper functions for RwasmtimeNativeModule

`RwasmtimeNativeModule_exports` <- function(self) {
  function() {
    .Call(savvy_RwasmtimeNativeModule_exports__impl, `self`)
  }
}

`RwasmtimeNativeModule_imports` <- function(self) {
  function() {
    .Call(savvy_RwasmtimeNativeModule_imports__impl, `self`)
  }
}

`RwasmtimeNativeModule_instantiate` <- function(self) {
  function(`memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`) {
    .savvy_wrap_RwasmtimeNativeInstance(.Call(savvy_RwasmtimeNativeModule_instantiate__impl, `self`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`))
  }
}

`RwasmtimeNativeModule_instantiate_callbacks` <- function(self) {
  function(`callback_modules`, `callback_names`, `callback_abis`, `callback_functions`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`) {
    .savvy_wrap_RwasmtimeNativeInstance(.Call(savvy_RwasmtimeNativeModule_instantiate_callbacks__impl, `self`, `callback_modules`, `callback_names`, `callback_abis`, `callback_functions`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`))
  }
}

`RwasmtimeNativeModule_instantiate_wasi_p1` <- function(self) {
  function(`args`, `env_names`, `env_values`, `preopen_guest`, `preopen_host`, `preopen_readonly`, `stdin`, `stdout`, `stderr`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`, `input`) {
    .savvy_wrap_RwasmtimeNativeInstance(.Call(savvy_RwasmtimeNativeModule_instantiate_wasi_p1__impl, `self`, `args`, `env_names`, `env_values`, `preopen_guest`, `preopen_host`, `preopen_readonly`, `stdin`, `stdout`, `stderr`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`, `input`))
  }
}

`RwasmtimeNativeModule_instantiate_wasi_p1_callbacks` <- function(self) {
  function(`callback_modules`, `callback_names`, `callback_abis`, `callback_functions`, `args`, `env_names`, `env_values`, `preopen_guest`, `preopen_host`, `preopen_readonly`, `stdin`, `stdout`, `stderr`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`, `input`) {
    .savvy_wrap_RwasmtimeNativeInstance(.Call(savvy_RwasmtimeNativeModule_instantiate_wasi_p1_callbacks__impl, `self`, `callback_modules`, `callback_names`, `callback_abis`, `callback_functions`, `args`, `env_names`, `env_values`, `preopen_guest`, `preopen_host`, `preopen_readonly`, `stdin`, `stdout`, `stderr`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`, `input`))
  }
}

`RwasmtimeNativeModule_serialize` <- function(self) {
  function() {
    .Call(savvy_RwasmtimeNativeModule_serialize__impl, `self`)
  }
}

`.savvy_wrap_RwasmtimeNativeModule` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`exports` <- `RwasmtimeNativeModule_exports`(ptr)
  e$`imports` <- `RwasmtimeNativeModule_imports`(ptr)
  e$`instantiate` <- `RwasmtimeNativeModule_instantiate`(ptr)
  e$`instantiate_callbacks` <- `RwasmtimeNativeModule_instantiate_callbacks`(ptr)
  e$`instantiate_wasi_p1` <- `RwasmtimeNativeModule_instantiate_wasi_p1`(ptr)
  e$`instantiate_wasi_p1_callbacks` <- `RwasmtimeNativeModule_instantiate_wasi_p1_callbacks`(ptr)
  e$`serialize` <- `RwasmtimeNativeModule_serialize`(ptr)

  class(e) <- c("Rwasmtime::RwasmtimeNativeModule", "RwasmtimeNativeModule", "savvy_Rwasmtime__sealed")
  e
}


#' Compiled core Wasm module owned by the Savvy adapter.
#' @noRd
`RwasmtimeNativeModule` <- new.env(parent = emptyenv())

### associated functions for RwasmtimeNativeModule



class(`RwasmtimeNativeModule`) <- c("Rwasmtime::RwasmtimeNativeModule__bundle", "savvy_Rwasmtime__sealed")

#' @export
`print.Rwasmtime::RwasmtimeNativeModule__bundle` <- function(x, ...) {
  cat('Rwasmtime::RwasmtimeNativeModule\n')
}

### wrapper functions for RwasmtimeNativeRuntime

`RwasmtimeNativeRuntime_call_core` <- function(self) {
  function(`module`, `export`, `args`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`) {
    .Call(savvy_RwasmtimeNativeRuntime_call_core__impl, `self`, `module`, `export`, `args`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`)
  }
}

`RwasmtimeNativeRuntime_compile_core` <- function(self) {
  function(`module`) {
    .savvy_wrap_RwasmtimeNativeModule(.Call(savvy_RwasmtimeNativeRuntime_compile_core__impl, `self`, `module`))
  }
}

`RwasmtimeNativeRuntime_component_exports` <- function(self) {
  function(`component`) {
    .Call(savvy_RwasmtimeNativeRuntime_component_exports__impl, `self`, `component`)
  }
}

`RwasmtimeNativeRuntime_component_imports` <- function(self) {
  function(`component`) {
    .Call(savvy_RwasmtimeNativeRuntime_component_imports__impl, `self`, `component`)
  }
}

`RwasmtimeNativeRuntime_deserialize_core` <- function(self) {
  function(`bytes`) {
    .savvy_wrap_RwasmtimeNativeModule(.Call(savvy_RwasmtimeNativeRuntime_deserialize_core__impl, `self`, `bytes`))
  }
}

`RwasmtimeNativeRuntime_instantiate_core` <- function(self) {
  function(`module`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`) {
    .savvy_wrap_RwasmtimeNativeInstance(.Call(savvy_RwasmtimeNativeRuntime_instantiate_core__impl, `self`, `module`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`))
  }
}

`RwasmtimeNativeRuntime_run_wasi_p1` <- function(self) {
  function(`module`, `args`, `env_names`, `env_values`, `preopen_guest`, `preopen_host`, `preopen_readonly`, `stdin`, `stdout`, `stderr`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`, `input`) {
    .Call(savvy_RwasmtimeNativeRuntime_run_wasi_p1__impl, `self`, `module`, `args`, `env_names`, `env_values`, `preopen_guest`, `preopen_host`, `preopen_readonly`, `stdin`, `stdout`, `stderr`, `memory_bytes`, `table_elements`, `instances`, `fuel`, `wall_time_ms`, `input`)
  }
}

`.savvy_wrap_RwasmtimeNativeRuntime` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`call_core` <- `RwasmtimeNativeRuntime_call_core`(ptr)
  e$`compile_core` <- `RwasmtimeNativeRuntime_compile_core`(ptr)
  e$`component_exports` <- `RwasmtimeNativeRuntime_component_exports`(ptr)
  e$`component_imports` <- `RwasmtimeNativeRuntime_component_imports`(ptr)
  e$`deserialize_core` <- `RwasmtimeNativeRuntime_deserialize_core`(ptr)
  e$`instantiate_core` <- `RwasmtimeNativeRuntime_instantiate_core`(ptr)
  e$`run_wasi_p1` <- `RwasmtimeNativeRuntime_run_wasi_p1`(ptr)

  class(e) <- c("Rwasmtime::RwasmtimeNativeRuntime", "RwasmtimeNativeRuntime", "savvy_Rwasmtime__sealed")
  e
}


#' Native Wasmtime runtime handle owned by the Savvy adapter.
#' @noRd
`RwasmtimeNativeRuntime` <- new.env(parent = emptyenv())

### associated functions for RwasmtimeNativeRuntime

`RwasmtimeNativeRuntime`$`build` <- function(`compiler_strategy`, `opt_level`, `parallel`, `component_model`, `component_model_async`, `simd`, `relaxed_simd`, `relaxed_simd_deterministic`, `bulk_memory`, `multi_memory`, `memory64`, `threads`, `exceptions`, `legacy_exceptions`, `gc`) {
  .savvy_wrap_RwasmtimeNativeRuntime(.Call(savvy_RwasmtimeNativeRuntime_build__impl, `compiler_strategy`, `opt_level`, `parallel`, `component_model`, `component_model_async`, `simd`, `relaxed_simd`, `relaxed_simd_deterministic`, `bulk_memory`, `multi_memory`, `memory64`, `threads`, `exceptions`, `legacy_exceptions`, `gc`))
}


class(`RwasmtimeNativeRuntime`) <- c("Rwasmtime::RwasmtimeNativeRuntime__bundle", "savvy_Rwasmtime__sealed")

#' @export
`print.Rwasmtime::RwasmtimeNativeRuntime__bundle` <- function(x, ...) {
  cat('Rwasmtime::RwasmtimeNativeRuntime\n')
}

